### ISSUE TITLE
Rest SDK not compatible with TLS 1.1/1.2 and Java 7

### ISSUE THREAD

**Issue by bvanalderweireldt** [zuora/rest-java-client#6]
Following the recent changes : [TLS change announcement](http://community.zuora.com/t5/Zuora-Announcements/Action-Required-Zuora-is-Disabling-TLS-1-0/ba-p/2177), the SDK is now not able to communicate with Zuora Sandbox.

%% No cached client session
**\* ClientHello, TLSv1
RandomCookie:  GMT: 1437827769 bytes = { 20, 26, 74, 107, 158, 240, 235, 156, 242, 158, 250, 78, 212, 46, 77, 166, 160, 28, 252, 1, 255, 178, 87, 175, 30, 18, 24, 190 }
Session ID:  {}
main, handling exception: java.net.SocketException: Connection reset
main, SEND TLSv1 ALERT:  fatal, description = unexpected_message
main, WRITE: TLSv1 Alert, length = 2
main, Exception sending alert: java.net.SocketException: Broken pipe
main, called closeSocket()
main, IOException in getSession():  java.net.SocketException: Connection reset
main, called close()

One way to it would be to update httpclient to 4.3.1 and refractor it using :
`SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
`

**Comment by hgschmie** [comment]
Thank you for this report. We have decided to deprecate this code base in favor of the new quickstart-java and codelibrary-java repositories. The old code is still available from the `legacy` branch of this repository but will no longer be supported.
